#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=8
#SBATCH --cpus-per-task=1
#SBATCH --partition=a100
#SBATCH --gres=gpu:1

#SBATCH --job-name=flan-pred

#SBATCH --time=01:00:00

#SBATCH -o t5flan/predict.out
#SBATCH -e t5flan/predict.err

conda activate torch
python predict.py